# Local dev environment

version: "3.8"
services:
  djangocities:
    build:
      context: django
      target: djangodev
    depends_on:
      - pgcities
    environment:
      - DEBUG=TRUE
      - DJANGO_SECRET_KEY=UNSAFELYpushDEVsecretsToGitbutITSnotFORprodSOwtv
      - POSTGRES_DB=${POSTGRES_DB-patryktech}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-patryktech}
      - POSTGRES_USER=${POSTGRES_USER-patryktech}
    restart: "no"
    volumes:
      - "./django/:/django"
  # Database
  pgcities:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB-djangocities}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-djangocities}
      - POSTGRES_USER=${POSTGRES_USER-djangocities}
    restart: "no"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
