os: linux
dist: xenial

language: python
python: 3.8
cache: pip

jobs:
  include:
    - name: "Django Test"
      install:
        - pip install -r sarcastic-sparrows/requirements/local.txt
      script:
        - pytest
    - name: "Lint"
      install:
        - pip install flake8
      script:
        - flake8 . --isolated --exclude=.cache,.venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox --max-line-length=119
