version: '3.8'

services:
  
  db:
    image: postgres:10.1-alpine  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: bash -c "pipenv run makemigrations-l && pipenv run migrate-l && pipenv run python3 Website/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
