on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker images
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          image_name: kmui2/silky-squirrels
          context: './silky-squirrels'

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'silky-squirrels'
          images: 'kmui2/silky-squirrels:latest'
          configuration-file: './silky-squirrels/docker-compose.prod.yml'

      - name: Azure logout
        run: |
          az logout
